GET https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODAyLCJlbWFpbCI6InRlc3RAZW1haWwubHQiLCJpYXQiOjE2NTY5NjQxNDJ9.GevfPx9pIiXyMaB7H5VkzbjbKXIHLNq-4w6UjEQF2KU

###

POST https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODAyLCJlbWFpbCI6InRlc3RAZW1haWwubHQiLCJpYXQiOjE2NTY5NjQxNDJ9.GevfPx9pIiXyMaB7H5VkzbjbKXIHLNq-4w6UjEQF2KU

{
"title": "Test",
"description": "tets"
}

###

POST https://autumn-delicate-wilderness.glitch.me/v1/auth/register 
Content-Type: application/json

{
"email": "test@email.lt", "password": "123456"
}

###

POST https://autumn-delicate-wilderness.glitch.me/v1/auth/login 
Content-Type: application/json

{
"email": "test@email.lt", "password": "123456"
}